name: TestCD
  
# Controls when the action will run. 
on:
    #allow manual trigger
    workflow_dispatch:

    # trigger on tagged push to main branch
    push:
        # branches:
        #   - main

jobs:
    build_for_testpypi:
      name: Build distribution
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: python3 -m pip install build --user
      
      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/


    testpypi-publish:
      name: Create TestPyPI release
      runs-on: ubuntu-latest
      needs: build_for_testpypi
      environment:
        name: testpypi_release
        url: https://test.pypi.org/p/iSparrowRecord
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
     
      steps:
      - name: download distribution builds
        uses: actions/download-artifact@v3
        with:
            name: python-package-distributions
            path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/